// Code generated by cmd/cli-gen. DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb/types"
	"github.com/sivchari/kumo/internal/cligen"
	"github.com/spf13/cobra"
	"os"
	"reflect"
)

func newDynamoDBCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "dynamodb",
		Short: "DynamoDB commands",
	}

	cmd.AddCommand(
		newDynamoDBBatchGetItemCmd(),
		newDynamoDBBatchWriteItemCmd(),
		newDynamoDBCreateTableCmd(),
		newDynamoDBDeleteTableCmd(),
		newDynamoDBDescribeContinuousBackupsCmd(),
		newDynamoDBDescribeTableCmd(),
		newDynamoDBDescribeTimeToLiveCmd(),
		newDynamoDBListTablesCmd(),
		newDynamoDBListTagsOfResourceCmd(),
		newDynamoDBTagResourceCmd(),
		newDynamoDBTransactGetItemsCmd(),
		newDynamoDBTransactWriteItemsCmd(),
		newDynamoDBUntagResourceCmd(),
		newDynamoDBUpdateTableCmd(),
		newDynamoDBUpdateTimeToLiveCmd(),
	)

	return cmd
}

func newDynamoDBBatchGetItemCmd() *cobra.Command {
	var requestItems string
	var returnConsumedCapacity string

	cmd := &cobra.Command{
		Use:   "batch-get-item",
		Short: "BatchGetItem",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := dynamodb.NewFromConfig(cfg, func(o *dynamodb.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &dynamodb.BatchGetItemInput{}

			if requestItems != "" {
				if err := json.Unmarshal([]byte(requestItems), &input.RequestItems); err != nil {
					return fmt.Errorf("batch-get-item: parse --request-items: %w", err)
				}
			}

			if returnConsumedCapacity != "" {
				input.ReturnConsumedCapacity = types.ReturnConsumedCapacity(returnConsumedCapacity)
			}

			out, err := client.BatchGetItem(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("batch-get-item failed: %w", err)
			}

			if err := json.NewEncoder(os.Stdout).Encode(out); err != nil {
				return fmt.Errorf("failed to encode output: %w", err)
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&requestItems, "request-items", "", "Request items (JSON)")

	cmd.Flags().StringVar(&returnConsumedCapacity, "return-consumed-capacity", "", "Return consumed capacity")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newDynamoDBBatchWriteItemCmd() *cobra.Command {
	var requestItems string
	var returnConsumedCapacity string
	var returnItemCollectionMetrics string

	cmd := &cobra.Command{
		Use:   "batch-write-item",
		Short: "BatchWriteItem",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := dynamodb.NewFromConfig(cfg, func(o *dynamodb.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &dynamodb.BatchWriteItemInput{}

			if requestItems != "" {
				if err := json.Unmarshal([]byte(requestItems), &input.RequestItems); err != nil {
					return fmt.Errorf("batch-write-item: parse --request-items: %w", err)
				}
			}

			if returnConsumedCapacity != "" {
				input.ReturnConsumedCapacity = types.ReturnConsumedCapacity(returnConsumedCapacity)
			}

			if returnItemCollectionMetrics != "" {
				input.ReturnItemCollectionMetrics = types.ReturnItemCollectionMetrics(returnItemCollectionMetrics)
			}

			out, err := client.BatchWriteItem(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("batch-write-item failed: %w", err)
			}

			if err := json.NewEncoder(os.Stdout).Encode(out); err != nil {
				return fmt.Errorf("failed to encode output: %w", err)
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&requestItems, "request-items", "", "Request items (JSON)")

	cmd.Flags().StringVar(&returnConsumedCapacity, "return-consumed-capacity", "", "Return consumed capacity")

	cmd.Flags().StringVar(&returnItemCollectionMetrics, "return-item-collection-metrics", "", "Return item collection metrics")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newDynamoDBCreateTableCmd() *cobra.Command {
	var tableName string
	var attributeDefinitions []string
	var billingMode string
	var deletionProtectionEnabled bool
	var globalSecondaryIndexes string
	var globalTableSettingsReplicationMode string
	var globalTableSourceArn string
	var keySchema []string
	var localSecondaryIndexes string
	var onDemandThroughput string
	var provisionedThroughput string
	var resourcePolicy string
	var sSESpecification string
	var streamSpecification string
	var tags []string
	var warmThroughput string

	cmd := &cobra.Command{
		Use:   "create-table",
		Short: "CreateTable",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := dynamodb.NewFromConfig(cfg, func(o *dynamodb.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &dynamodb.CreateTableInput{}

			if tableName != "" {
				input.TableName = aws.String(tableName)
			}

			for _, raw := range attributeDefinitions {
				var val types.AttributeDefinition
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), raw); err != nil {
					return fmt.Errorf("create-table: parse --attribute-definitions: %w", err)
				}
				input.AttributeDefinitions = append(input.AttributeDefinitions, val)
			}

			if billingMode != "" {
				input.BillingMode = types.BillingMode(billingMode)
			}

			if deletionProtectionEnabled {
				input.DeletionProtectionEnabled = aws.Bool(deletionProtectionEnabled)
			}

			if globalSecondaryIndexes != "" {
				if err := json.Unmarshal([]byte(globalSecondaryIndexes), &input.GlobalSecondaryIndexes); err != nil {
					return fmt.Errorf("create-table: parse --global-secondary-indexes: %w", err)
				}
			}

			if globalTableSettingsReplicationMode != "" {
				input.GlobalTableSettingsReplicationMode = types.GlobalTableSettingsReplicationMode(globalTableSettingsReplicationMode)
			}

			if globalTableSourceArn != "" {
				input.GlobalTableSourceArn = aws.String(globalTableSourceArn)
			}

			for _, raw := range keySchema {
				var val types.KeySchemaElement
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), raw); err != nil {
					return fmt.Errorf("create-table: parse --key-schema: %w", err)
				}
				input.KeySchema = append(input.KeySchema, val)
			}

			if localSecondaryIndexes != "" {
				if err := json.Unmarshal([]byte(localSecondaryIndexes), &input.LocalSecondaryIndexes); err != nil {
					return fmt.Errorf("create-table: parse --local-secondary-indexes: %w", err)
				}
			}

			if onDemandThroughput != "" {
				var val types.OnDemandThroughput
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), onDemandThroughput); err != nil {
					return fmt.Errorf("create-table: parse --on-demand-throughput: %w", err)
				}
				input.OnDemandThroughput = &val
			}

			if provisionedThroughput != "" {
				var val types.ProvisionedThroughput
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), provisionedThroughput); err != nil {
					return fmt.Errorf("create-table: parse --provisioned-throughput: %w", err)
				}
				input.ProvisionedThroughput = &val
			}

			if resourcePolicy != "" {
				input.ResourcePolicy = aws.String(resourcePolicy)
			}

			if sSESpecification != "" {
				var val types.SSESpecification
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), sSESpecification); err != nil {
					return fmt.Errorf("create-table: parse --sse-specification: %w", err)
				}
				input.SSESpecification = &val
			}

			if streamSpecification != "" {
				var val types.StreamSpecification
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), streamSpecification); err != nil {
					return fmt.Errorf("create-table: parse --stream-specification: %w", err)
				}
				input.StreamSpecification = &val
			}

			for _, raw := range tags {
				var val types.Tag
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), raw); err != nil {
					return fmt.Errorf("create-table: parse --tags: %w", err)
				}
				input.Tags = append(input.Tags, val)
			}

			if warmThroughput != "" {
				var val types.WarmThroughput
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), warmThroughput); err != nil {
					return fmt.Errorf("create-table: parse --warm-throughput: %w", err)
				}
				input.WarmThroughput = &val
			}

			out, err := client.CreateTable(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("create-table failed: %w", err)
			}

			if err := json.NewEncoder(os.Stdout).Encode(out); err != nil {
				return fmt.Errorf("failed to encode output: %w", err)
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&tableName, "table-name", "", "Table name")

	cmd.Flags().StringArrayVar(&attributeDefinitions, "attribute-definitions", nil, "Attribute definitions (key=value,key2=value2, repeatable)")

	cmd.Flags().StringVar(&billingMode, "billing-mode", "", "Billing mode")

	cmd.Flags().BoolVar(&deletionProtectionEnabled, "deletion-protection-enabled", false, "Deletion protection enabled")

	cmd.Flags().StringVar(&globalSecondaryIndexes, "global-secondary-indexes", "", "Global secondary indexes (JSON)")

	cmd.Flags().StringVar(&globalTableSettingsReplicationMode, "global-table-settings-replication-mode", "", "Global table settings replication mode")

	cmd.Flags().StringVar(&globalTableSourceArn, "global-table-source-arn", "", "Global table source arn")

	cmd.Flags().StringArrayVar(&keySchema, "key-schema", nil, "Key schema (key=value,key2=value2, repeatable)")

	cmd.Flags().StringVar(&localSecondaryIndexes, "local-secondary-indexes", "", "Local secondary indexes (JSON)")

	cmd.Flags().StringVar(&onDemandThroughput, "on-demand-throughput", "", "On demand throughput (key=value,key2=value2)")

	cmd.Flags().StringVar(&provisionedThroughput, "provisioned-throughput", "", "Provisioned throughput (key=value,key2=value2)")

	cmd.Flags().StringVar(&resourcePolicy, "resource-policy", "", "Resource policy")

	cmd.Flags().StringVar(&sSESpecification, "sse-specification", "", "Sse specification (key=value,key2=value2)")

	cmd.Flags().StringVar(&streamSpecification, "stream-specification", "", "Stream specification (key=value,key2=value2)")

	cmd.Flags().StringArrayVar(&tags, "tags", nil, "Tags (key=value,key2=value2, repeatable)")

	cmd.Flags().StringVar(&warmThroughput, "warm-throughput", "", "Warm throughput (key=value,key2=value2)")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newDynamoDBDeleteTableCmd() *cobra.Command {
	var tableName string

	cmd := &cobra.Command{
		Use:   "delete-table",
		Short: "DeleteTable",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := dynamodb.NewFromConfig(cfg, func(o *dynamodb.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &dynamodb.DeleteTableInput{}

			if tableName != "" {
				input.TableName = aws.String(tableName)
			}

			out, err := client.DeleteTable(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("delete-table failed: %w", err)
			}

			if err := json.NewEncoder(os.Stdout).Encode(out); err != nil {
				return fmt.Errorf("failed to encode output: %w", err)
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&tableName, "table-name", "", "Table name")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newDynamoDBDescribeContinuousBackupsCmd() *cobra.Command {
	var tableName string

	cmd := &cobra.Command{
		Use:   "describe-continuous-backups",
		Short: "DescribeContinuousBackups",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := dynamodb.NewFromConfig(cfg, func(o *dynamodb.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &dynamodb.DescribeContinuousBackupsInput{}

			if tableName != "" {
				input.TableName = aws.String(tableName)
			}

			out, err := client.DescribeContinuousBackups(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("describe-continuous-backups failed: %w", err)
			}

			if err := json.NewEncoder(os.Stdout).Encode(out); err != nil {
				return fmt.Errorf("failed to encode output: %w", err)
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&tableName, "table-name", "", "Table name")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newDynamoDBDescribeTableCmd() *cobra.Command {
	var tableName string

	cmd := &cobra.Command{
		Use:   "describe-table",
		Short: "DescribeTable",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := dynamodb.NewFromConfig(cfg, func(o *dynamodb.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &dynamodb.DescribeTableInput{}

			if tableName != "" {
				input.TableName = aws.String(tableName)
			}

			out, err := client.DescribeTable(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("describe-table failed: %w", err)
			}

			if err := json.NewEncoder(os.Stdout).Encode(out); err != nil {
				return fmt.Errorf("failed to encode output: %w", err)
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&tableName, "table-name", "", "Table name")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newDynamoDBDescribeTimeToLiveCmd() *cobra.Command {
	var tableName string

	cmd := &cobra.Command{
		Use:   "describe-time-to-live",
		Short: "DescribeTimeToLive",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := dynamodb.NewFromConfig(cfg, func(o *dynamodb.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &dynamodb.DescribeTimeToLiveInput{}

			if tableName != "" {
				input.TableName = aws.String(tableName)
			}

			out, err := client.DescribeTimeToLive(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("describe-time-to-live failed: %w", err)
			}

			if err := json.NewEncoder(os.Stdout).Encode(out); err != nil {
				return fmt.Errorf("failed to encode output: %w", err)
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&tableName, "table-name", "", "Table name")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newDynamoDBListTablesCmd() *cobra.Command {
	var exclusiveStartTableName string
	var limit int32

	cmd := &cobra.Command{
		Use:   "list-tables",
		Short: "ListTables",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := dynamodb.NewFromConfig(cfg, func(o *dynamodb.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &dynamodb.ListTablesInput{}

			if exclusiveStartTableName != "" {
				input.ExclusiveStartTableName = aws.String(exclusiveStartTableName)
			}

			if limit != 0 {
				input.Limit = aws.Int32(limit)
			}

			out, err := client.ListTables(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("list-tables failed: %w", err)
			}

			if err := json.NewEncoder(os.Stdout).Encode(out); err != nil {
				return fmt.Errorf("failed to encode output: %w", err)
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&exclusiveStartTableName, "exclusive-start-table-name", "", "Exclusive start table name")

	cmd.Flags().Int32Var(&limit, "limit", 0, "Limit")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newDynamoDBListTagsOfResourceCmd() *cobra.Command {
	var resourceArn string
	var nextToken string

	cmd := &cobra.Command{
		Use:   "list-tags-of-resource",
		Short: "ListTagsOfResource",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := dynamodb.NewFromConfig(cfg, func(o *dynamodb.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &dynamodb.ListTagsOfResourceInput{}

			if resourceArn != "" {
				input.ResourceArn = aws.String(resourceArn)
			}

			if nextToken != "" {
				input.NextToken = aws.String(nextToken)
			}

			out, err := client.ListTagsOfResource(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("list-tags-of-resource failed: %w", err)
			}

			if err := json.NewEncoder(os.Stdout).Encode(out); err != nil {
				return fmt.Errorf("failed to encode output: %w", err)
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&resourceArn, "resource-arn", "", "Resource arn")

	cmd.Flags().StringVar(&nextToken, "next-token", "", "Next token")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newDynamoDBTagResourceCmd() *cobra.Command {
	var resourceArn string
	var tags []string

	cmd := &cobra.Command{
		Use:   "tag-resource",
		Short: "TagResource",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := dynamodb.NewFromConfig(cfg, func(o *dynamodb.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &dynamodb.TagResourceInput{}

			if resourceArn != "" {
				input.ResourceArn = aws.String(resourceArn)
			}

			for _, raw := range tags {
				var val types.Tag
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), raw); err != nil {
					return fmt.Errorf("tag-resource: parse --tags: %w", err)
				}
				input.Tags = append(input.Tags, val)
			}

			_, err = client.TagResource(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("tag-resource failed: %w", err)
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&resourceArn, "resource-arn", "", "Resource arn")

	cmd.Flags().StringArrayVar(&tags, "tags", nil, "Tags (key=value,key2=value2, repeatable)")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newDynamoDBTransactGetItemsCmd() *cobra.Command {
	var transactItems string
	var returnConsumedCapacity string

	cmd := &cobra.Command{
		Use:   "transact-get-items",
		Short: "TransactGetItems",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := dynamodb.NewFromConfig(cfg, func(o *dynamodb.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &dynamodb.TransactGetItemsInput{}

			if transactItems != "" {
				if err := json.Unmarshal([]byte(transactItems), &input.TransactItems); err != nil {
					return fmt.Errorf("transact-get-items: parse --transact-items: %w", err)
				}
			}

			if returnConsumedCapacity != "" {
				input.ReturnConsumedCapacity = types.ReturnConsumedCapacity(returnConsumedCapacity)
			}

			out, err := client.TransactGetItems(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("transact-get-items failed: %w", err)
			}

			if err := json.NewEncoder(os.Stdout).Encode(out); err != nil {
				return fmt.Errorf("failed to encode output: %w", err)
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&transactItems, "transact-items", "", "Transact items (JSON)")

	cmd.Flags().StringVar(&returnConsumedCapacity, "return-consumed-capacity", "", "Return consumed capacity")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newDynamoDBTransactWriteItemsCmd() *cobra.Command {
	var transactItems string
	var clientRequestToken string
	var returnConsumedCapacity string
	var returnItemCollectionMetrics string

	cmd := &cobra.Command{
		Use:   "transact-write-items",
		Short: "TransactWriteItems",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := dynamodb.NewFromConfig(cfg, func(o *dynamodb.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &dynamodb.TransactWriteItemsInput{}

			if transactItems != "" {
				if err := json.Unmarshal([]byte(transactItems), &input.TransactItems); err != nil {
					return fmt.Errorf("transact-write-items: parse --transact-items: %w", err)
				}
			}

			if clientRequestToken != "" {
				input.ClientRequestToken = aws.String(clientRequestToken)
			}

			if returnConsumedCapacity != "" {
				input.ReturnConsumedCapacity = types.ReturnConsumedCapacity(returnConsumedCapacity)
			}

			if returnItemCollectionMetrics != "" {
				input.ReturnItemCollectionMetrics = types.ReturnItemCollectionMetrics(returnItemCollectionMetrics)
			}

			out, err := client.TransactWriteItems(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("transact-write-items failed: %w", err)
			}

			if err := json.NewEncoder(os.Stdout).Encode(out); err != nil {
				return fmt.Errorf("failed to encode output: %w", err)
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&transactItems, "transact-items", "", "Transact items (JSON)")

	cmd.Flags().StringVar(&clientRequestToken, "client-request-token", "", "Client request token")

	cmd.Flags().StringVar(&returnConsumedCapacity, "return-consumed-capacity", "", "Return consumed capacity")

	cmd.Flags().StringVar(&returnItemCollectionMetrics, "return-item-collection-metrics", "", "Return item collection metrics")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newDynamoDBUntagResourceCmd() *cobra.Command {
	var resourceArn string
	var tagKeys []string

	cmd := &cobra.Command{
		Use:   "untag-resource",
		Short: "UntagResource",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := dynamodb.NewFromConfig(cfg, func(o *dynamodb.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &dynamodb.UntagResourceInput{}

			if resourceArn != "" {
				input.ResourceArn = aws.String(resourceArn)
			}

			if len(tagKeys) > 0 {
				input.TagKeys = tagKeys
			}

			_, err = client.UntagResource(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("untag-resource failed: %w", err)
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&resourceArn, "resource-arn", "", "Resource arn")

	cmd.Flags().StringArrayVar(&tagKeys, "tag-keys", nil, "Tag keys")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newDynamoDBUpdateTableCmd() *cobra.Command {
	var tableName string
	var attributeDefinitions []string
	var billingMode string
	var deletionProtectionEnabled bool
	var globalSecondaryIndexUpdates string
	var globalTableSettingsReplicationMode string
	var globalTableWitnessUpdates string
	var multiRegionConsistency string
	var onDemandThroughput string
	var provisionedThroughput string
	var replicaUpdates string
	var sSESpecification string
	var streamSpecification string
	var tableClass string
	var warmThroughput string

	cmd := &cobra.Command{
		Use:   "update-table",
		Short: "UpdateTable",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := dynamodb.NewFromConfig(cfg, func(o *dynamodb.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &dynamodb.UpdateTableInput{}

			if tableName != "" {
				input.TableName = aws.String(tableName)
			}

			for _, raw := range attributeDefinitions {
				var val types.AttributeDefinition
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), raw); err != nil {
					return fmt.Errorf("update-table: parse --attribute-definitions: %w", err)
				}
				input.AttributeDefinitions = append(input.AttributeDefinitions, val)
			}

			if billingMode != "" {
				input.BillingMode = types.BillingMode(billingMode)
			}

			if deletionProtectionEnabled {
				input.DeletionProtectionEnabled = aws.Bool(deletionProtectionEnabled)
			}

			if globalSecondaryIndexUpdates != "" {
				if err := json.Unmarshal([]byte(globalSecondaryIndexUpdates), &input.GlobalSecondaryIndexUpdates); err != nil {
					return fmt.Errorf("update-table: parse --global-secondary-index-updates: %w", err)
				}
			}

			if globalTableSettingsReplicationMode != "" {
				input.GlobalTableSettingsReplicationMode = types.GlobalTableSettingsReplicationMode(globalTableSettingsReplicationMode)
			}

			if globalTableWitnessUpdates != "" {
				if err := json.Unmarshal([]byte(globalTableWitnessUpdates), &input.GlobalTableWitnessUpdates); err != nil {
					return fmt.Errorf("update-table: parse --global-table-witness-updates: %w", err)
				}
			}

			if multiRegionConsistency != "" {
				input.MultiRegionConsistency = types.MultiRegionConsistency(multiRegionConsistency)
			}

			if onDemandThroughput != "" {
				var val types.OnDemandThroughput
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), onDemandThroughput); err != nil {
					return fmt.Errorf("update-table: parse --on-demand-throughput: %w", err)
				}
				input.OnDemandThroughput = &val
			}

			if provisionedThroughput != "" {
				var val types.ProvisionedThroughput
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), provisionedThroughput); err != nil {
					return fmt.Errorf("update-table: parse --provisioned-throughput: %w", err)
				}
				input.ProvisionedThroughput = &val
			}

			if replicaUpdates != "" {
				if err := json.Unmarshal([]byte(replicaUpdates), &input.ReplicaUpdates); err != nil {
					return fmt.Errorf("update-table: parse --replica-updates: %w", err)
				}
			}

			if sSESpecification != "" {
				var val types.SSESpecification
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), sSESpecification); err != nil {
					return fmt.Errorf("update-table: parse --sse-specification: %w", err)
				}
				input.SSESpecification = &val
			}

			if streamSpecification != "" {
				var val types.StreamSpecification
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), streamSpecification); err != nil {
					return fmt.Errorf("update-table: parse --stream-specification: %w", err)
				}
				input.StreamSpecification = &val
			}

			if tableClass != "" {
				input.TableClass = types.TableClass(tableClass)
			}

			if warmThroughput != "" {
				var val types.WarmThroughput
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), warmThroughput); err != nil {
					return fmt.Errorf("update-table: parse --warm-throughput: %w", err)
				}
				input.WarmThroughput = &val
			}

			out, err := client.UpdateTable(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("update-table failed: %w", err)
			}

			if err := json.NewEncoder(os.Stdout).Encode(out); err != nil {
				return fmt.Errorf("failed to encode output: %w", err)
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&tableName, "table-name", "", "Table name")

	cmd.Flags().StringArrayVar(&attributeDefinitions, "attribute-definitions", nil, "Attribute definitions (key=value,key2=value2, repeatable)")

	cmd.Flags().StringVar(&billingMode, "billing-mode", "", "Billing mode")

	cmd.Flags().BoolVar(&deletionProtectionEnabled, "deletion-protection-enabled", false, "Deletion protection enabled")

	cmd.Flags().StringVar(&globalSecondaryIndexUpdates, "global-secondary-index-updates", "", "Global secondary index updates (JSON)")

	cmd.Flags().StringVar(&globalTableSettingsReplicationMode, "global-table-settings-replication-mode", "", "Global table settings replication mode")

	cmd.Flags().StringVar(&globalTableWitnessUpdates, "global-table-witness-updates", "", "Global table witness updates (JSON)")

	cmd.Flags().StringVar(&multiRegionConsistency, "multi-region-consistency", "", "Multi region consistency")

	cmd.Flags().StringVar(&onDemandThroughput, "on-demand-throughput", "", "On demand throughput (key=value,key2=value2)")

	cmd.Flags().StringVar(&provisionedThroughput, "provisioned-throughput", "", "Provisioned throughput (key=value,key2=value2)")

	cmd.Flags().StringVar(&replicaUpdates, "replica-updates", "", "Replica updates (JSON)")

	cmd.Flags().StringVar(&sSESpecification, "sse-specification", "", "Sse specification (key=value,key2=value2)")

	cmd.Flags().StringVar(&streamSpecification, "stream-specification", "", "Stream specification (key=value,key2=value2)")

	cmd.Flags().StringVar(&tableClass, "table-class", "", "Table class")

	cmd.Flags().StringVar(&warmThroughput, "warm-throughput", "", "Warm throughput (key=value,key2=value2)")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}

func newDynamoDBUpdateTimeToLiveCmd() *cobra.Command {
	var tableName string
	var timeToLiveSpecification string

	cmd := &cobra.Command{
		Use:   "update-time-to-live",
		Short: "UpdateTimeToLive",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cfg, err := newAWSConfig(cmd.Context())
			if err != nil {
				return err
			}

			client := dynamodb.NewFromConfig(cfg, func(o *dynamodb.Options) {
				o.BaseEndpoint = aws.String(endpointURL)
			})

			input := &dynamodb.UpdateTimeToLiveInput{}

			if tableName != "" {
				input.TableName = aws.String(tableName)
			}

			if timeToLiveSpecification != "" {
				var val types.TimeToLiveSpecification
				if err := cligen.SetFieldsFromKV(reflect.ValueOf(&val).Elem(), timeToLiveSpecification); err != nil {
					return fmt.Errorf("update-time-to-live: parse --time-to-live-specification: %w", err)
				}
				input.TimeToLiveSpecification = &val
			}

			_, err = client.UpdateTimeToLive(cmd.Context(), input)
			if err != nil {
				return fmt.Errorf("update-time-to-live failed: %w", err)
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&tableName, "table-name", "", "Table name")

	cmd.Flags().StringVar(&timeToLiveSpecification, "time-to-live-specification", "", "Time to live specification (key=value,key2=value2)")

	cmd.Flags().String("region", "", "Region override (ignored)")

	return cmd
}
